blog/urls.py
from django.urls import path
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from .views import (
                    BlogAPIView, BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, 
                    BlogDeleteView, UserBlogListView, register, BlogDetailAPIView
                    )   

urlpatterns = [
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    # For getting all blogs and creating a new blog
    path('api/blogs/', BlogAPIView.as_view({'get': 'get_all', 'post': 'post'}), name='api-blogs'), 
    path('api/blogs/<int:pk>/', BlogDetailAPIView.as_view({'get': 'get', 'put': 'put', 'delete': 'delete'}), name='api-blog-detail'),  
    
    path('register/', register, name='register'),
    path('', BlogListView.as_view(), name='blog-list'),
    path('my-blogs/', UserBlogListView.as_view(), name='user-blog-list'),
    path('blogs/<int:pk>/', BlogDetailView.as_view(), name='blog-detail'),
    path('blogs/create/', BlogCreateView.as_view(), name='blog-create'),
    path('blogs/<int:pk>/edit/', BlogUpdateView.as_view(), name='blog-edit'),
    path('blogs/<int:pk>/delete/', BlogDeleteView.as_view(), name='blog-delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from rest_framework.permissions import AllowAny
from rest_framework_simplejwt.authentication import JWTAuthentication
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Your Project API",
        default_version='v1',
        description="API documentation for your project",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@yourdomain.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(AllowAny,),
    authentication_classes=(JWTAuthentication,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('django.contrib.auth.urls')),

    # Swagger
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User


class Tag(models.Model):
    name = models.CharField(max_length=32, unique=True)

    def __str__(self) -> str:
        return "{}".format(self.name)


class Blog(models.Model):
    title = models.CharField(max_length=128)
    context = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag, related_name='tags')
    published_date = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f"{self.title} by {self.author.last_name} {self.author.first_name}"

blog/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Blog

class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'context', 'tags']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter blog title'}),
            'context': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Write your blog content here...', 'rows': 6}),
        }


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    password_confirm = forms.CharField(widget=forms.PasswordInput, label="Confirm Password")

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'password']

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        password_confirm = cleaned_data.get("password_confirm")

        if password and password_confirm:
            if password != password_confirm:
                self.add_error('password_confirm', "Passwords do not match.")

        return cleaned_data

blog/views.py
from rest_framework.viewsets import ViewSet
from rest_framework.response import Response
from rest_framework import status
from rest_framework.permissions import AllowAny, IsAuthenticated

from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.models import User
from django.db.models.functions import TruncMonth
from django.contrib import messages
from django.db.models import Q
from django.urls import reverse_lazy
from django.shortcuts import render, redirect

from drf_yasg.utils import swagger_auto_schema
from drf_yasg import openapi

from .models import Blog, Tag
from .serializers import BlogSerializer, BlogFilterSerializer
from .forms import BlogForm, UserRegistrationForm
from .utils import get_blog_or_404


class BlogAPIView(ViewSet):
    @swagger_auto_schema(
        operation_description="Get all blogs with optional filters (start_date, end_date, tag, user)",
        responses={200: BlogSerializer(many=True)},
        manual_parameters=[
            openapi.Parameter(
                'start_date', openapi.IN_QUERY, 
                description="Filter blogs created on or after this date (format: YYYY-MM-DD)",
                type=openapi.TYPE_STRING,
                format=openapi.FORMAT_DATE,
            ),
            openapi.Parameter(
                'end_date', openapi.IN_QUERY, 
                description="Filter blogs created on or before this date (format: YYYY-MM-DD)",
                type=openapi.TYPE_STRING,
                format=openapi.FORMAT_DATE,
            ),
            openapi.Parameter(
                'tag', openapi.IN_QUERY, 
                description="Filter blogs by tag name (case-insensitive)",
                type=openapi.TYPE_STRING,
            ),
            openapi.Parameter(
                'user', openapi.IN_QUERY, 
                description="Filter blogs by author's username or first name or last name (case-insensitive)",
                type=openapi.TYPE_STRING,
            ),
        ],
        tags=['Blogs'],
    )
    def get_all(self, request):
        filter_serializer = BlogFilterSerializer(data=request.query_params)
        filter_serializer.is_valid(raise_exception=True)
        filters = filter_serializer.validated_data
        blogs = Blog.objects.all()

        if 'start_date' in filters:
            blogs = blogs.filter(published_date__date__gte=filters['start_date'])
        if 'end_date' in filters:
            blogs = blogs.filter(published_date__date__lte=filters['end_date'])
        if 'tag' in filters:
            blogs = blogs.filter(tags__name__icontains=filters['tag'])
        if 'user' in filters:
            user_param = filters['user']
            blogs = blogs.filter(Q(author__first_name__icontains=user_param) | Q(author__last_name__icontains=user_param) \
                                 | Q(author__username__icontains=user_param))
        serializer = BlogSerializer(blogs, many=True)
        return Response(data=serializer.data, status=status.HTTP_200_OK)
    
    @swagger_auto_schema(
        operation_description="Get user's blogs with optional filters (start_date, end_date, tag)",
        responses={200: BlogSerializer(many=True)},
        tags=['Blogs'],
    )
    def get_user_blogs(self, request):
        filter_serializer = BlogFilterSerializer(data=request.query_params)
        filter_serializer.is_valid(raise_exception=True)
        filters = filter_serializer.validated_data

        if not request.user.is_authenticated:
            return Response(data={"message": "You must be logged in to view your blogs."}, status=status.HTTP_401_UNAUTHORIZED)
        
        blogs = Blog.objects.filter(author=request.user)

        if 'start_date' in filters:
            blogs = blogs.filter(published_date__date__gte=filters['start_date'])
        if 'end_date' in filters:
            blogs = blogs.filter(published_date__date__lte=filters['end_date'])
        if 'tag' in filters:
            blogs = blogs.filter(tags__name__icontains=filters['tag'])

        serializer = BlogSerializer(blogs, many=True)
        return Response(data=serializer.data, status=status.HTTP_200_OK)

    @swagger_auto_schema(
        operation_description="Create a new blog",
        request_body=BlogSerializer,
        responses={201: BlogSerializer},
        tags=['Blogs'],
    )
    def post(self, request):
        if not request.user.is_authenticated:
            return Response(data={"message": "You must be logged in to create a blog."}, status=status.HTTP_401_UNAUTHORIZED)
        request.data['author'] = request.user.id
        serializer = BlogSerializer(data=request.data)

        if serializer.is_valid():
            serializer.save()
            return Response(data=serializer.data, status=status.HTTP_201_CREATED)
        return Response(data=serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    

class BlogDetailAPIView(ViewSet):
    @swagger_auto_schema(
        operation_description="Get a specific blog",
        responses={200: BlogSerializer},
        tags=['Blogs'],
    )
    def get(self, request, pk):
        blog = get_blog_or_404(pk)
        serializer = BlogSerializer(blog)
        return Response(data=serializer.data, status=status.HTTP_200_OK)

    @swagger_auto_schema(
        operation_description="Retrieve a specific blog",
        request_body=BlogSerializer,
        responses={200: BlogSerializer},
        tags=['Blogs'],
    )
    def put(self, request, pk):
        blog = get_blog_or_404(pk)
        if request.user != blog.author:
            return Response(data={"message": "You do not have permission to edit this blog."}, status=status.HTTP_403_FORBIDDEN)
        
        serializer = BlogSerializer(blog, data=request.data, partial=True)
        return Response(data=serializer.data, status=status.HTTP_200_OK)

    @swagger_auto_schema(
        operation_description="Delete a blog post",
        responses={204: "No Content"},
        tags=['Blogs'],
    )
    def delete(self, request, pk):
        blog = get_blog_or_404(pk)
        if request.user != blog.author:
            return Response(data={"message": "You do not have permission to delete this blog."}, status=status.HTTP_403_FORBIDDEN)

        blog.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)


# Django HTML Views
# Views for Templates
class BlogListView(ListView):
    model = Blog
    template_name = 'blog_list.html'
    context_object_name = 'blogs'
    permission_classes = [AllowAny]

    def get_queryset(self):
        queryset = Blog.objects.all().annotate(published_month=TruncMonth('published_date')).order_by('-published_month', '-published_date')

        # Filter by tag
        tag_id = self.request.GET.get('tag')
        if tag_id:
            queryset = queryset.filter(tags__id=tag_id)

        # Filter by author
        author_id = self.request.GET.get('author')
        if author_id:
            queryset = queryset.filter(author__id=author_id)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tags'] = Tag.objects.all()  # List of all tags
        context['authors'] = User.objects.all()
        
        return context
    

class UserBlogListView(ListView):
    model = Blog
    template_name = 'user_blog_list.html'
    context_object_name = 'blogs'
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        queryset = Blog.objects.filter(author=self.request.user).annotate(published_month=TruncMonth('published_date')).order_by('-published_month', '-published_date')
        return queryset
    

class BlogDetailView(DetailView):
    model = Blog
    template_name = 'blog_detail.html'
    context_object_name = 'blog'
    permission_classes = [AllowAny]

class BlogCreateView(CreateView):
    model = Blog
    form_class = BlogForm
    template_name = 'blog_form.html'
    success_url = reverse_lazy('blog-list')
    permission_classes = [IsAuthenticated]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tags'] = Tag.objects.all()
        return context

    def form_valid(self, form):
        form.instance.author = self.request.user
        response = super().form_valid(form)
        self.object.tags.set(self.request.POST.getlist('tags'))
        return response


class BlogUpdateView(UpdateView):
    model = Blog
    form_class = BlogForm
    template_name = 'blog_form.html'
    success_url = reverse_lazy('blog-list')
    permission_classes = [IsAuthenticated]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        blog = self.object  # Get the current blog instance
        context['tags'] = Tag.objects.all()  # All available tags
        context['selected_tags'] = blog.tags.values_list('id', flat=True)  # Currently selected tags
        return context

    def dispatch(self, request, *args, **kwargs):
        blog = self.get_object()
        if blog.author != request.user:
            return render(request, 'errors/permission_denied.html', status=403)
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        response = super().form_valid(form)
        self.object.tags.set(self.request.POST.getlist('tags'))
        return response


class BlogDeleteView(DeleteView):
    model = Blog
    template_name = 'blog_confirm_delete.html'
    success_url = '/'
    permission_classes = [IsAuthenticated]

    def dispatch(self, request, *args, **kwargs):
        blog = self.get_object()
        if blog.author != request.user:
            return render(request, 'errors/permission_denied.html', status=403)
        return super().dispatch(request, *args, **kwargs)
    
# registration
def register(request):
    form = UserRegistrationForm()
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)

blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}My Blog{% endblock %}</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <style>
        /* Ensure full height for the body and html */
        html, body {
            height: 100%;
            margin: 0;
        }
        /* Push footer to the bottom */
        .wrapper {
            display: flex;
            flex-direction: column;
            min-height: 100vh; /* Full height for the wrapper */
        }
        .content {
            flex: 1; /* Take remaining space */
        }
        /* styles.css or your main CSS file */
        .errorlist {
            color: red;  /* Set text color to red */
            margin-top: 0.5rem;  /* Add some space above the error message */
        }
    </style>
</head>
<body>
    <div class="wrapper">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="{% url 'blog-list' %}">Blogs</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                {% if user.is_authenticated %}
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'user-blog-list' %}">My Blogs</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'blog-create' %}">Create Blog</a>
                        </li>
                        <li class="nav-item">
                            <form action="{% url 'logout' %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-link nav-link">Logout</button>
                            </form>
                        </li>
                    </ul>
                </div>
                <span class="navbar-text text-white">{{ user.username|upper }}</span>
                {% else %}
                <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'login' %}">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'register' %}">Register</a>
                        </li>
                    </ul>
                </div>
                {% endif %}
            </div>
        </nav>
  
        <div class="content">
            <div class="container mt-4">
                {% block content %}{% endblock %}
            </div>
        </div>

        <footer class="footer py-3 bg-light">
            <div class="container text-center">
                <span class="text-muted">&copy; 2024 My Blog. All rights reserved.</span>
            </div>
        </footer>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

blog/templates/blog_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Delete Blog{% endblock %}

{% block content %}
<h2>Are you sure you want to delete this blog post?</h2>
<p><strong>{{ blog.title }}</strong> by {{ blog.author }}</p>
<form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Yes, Delete</button>
    <a href="{% url 'blog-list' %}" class="btn btn-secondary">No, Go Back</a>
</form>
{% endblock %}

blog/templates/blog_detail.html
{% extends "base.html" %}

{% block title %}{{ blog.title }} - My Blog{% endblock %}

{% block content %}
<div class="container mt-4">
    <h1 class="display-4">{{ blog.title }}</h1>
    <p class="text-muted">Published on {{ blog.published_date|date:"F j, Y" }}</p>
    <div class="tags mt-4">
        <h5>Tags:</h5>
        {% for tag in blog.tags.all %}
            <span class="badge badge-info p-2">{{ tag.name }}</span>
        {% endfor %}
    </div>
    
    <div class="blog-content">
        <p>{{ blog.context|linebreaks }}</p> <!-- Using linebreaks filter for formatting -->
    </div>

    {% if user == blog.author %}
    <div class="mt-4">
        <a href="{% url 'blog-list' %}" class="btn btn-primary">Back to Blog List</a>
        <a href="{% url 'blog-edit' blog.id %}" class="btn btn-secondary">Edit Blog</a>
        <form action="{% url 'blog-delete' blog.id %}" method="post" style="display:inline;">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Delete Blog</button>
        </form>
    </div>
    {% endif %} 
</div>
{% endblock %}

blog/templates/blog_form.html
{% extends 'base.html' %}

{% block title %}Form{% endblock %}

{% block content %}
<div class="container mt-5">
    <h2 class="text-center">{% if object %}Edit Blog: {{ object.title }}{% else %}Create New Blog{% endif %}</h2>
    {% if request.user.is_authenticated %}
    <form method="post">
        {% csrf_token %}
        
        <div class="mb-3">
            <label for="id_title" class="form-label">Title:</label>
            {{ form.title }}  <!-- Render the title field -->
        </div>

        <div class="mb-3">
            <label for="id_context" class="form-label">Content:</label>
            {{ form.context }}  <!-- Render the content field -->
        </div>

        <div class="mb-5">
            <label>Tags:</label>
            <div id="tag-buttons">
                {% for tag in tags %}
                    <label class="btn btn-outline-primary {% if tag.id in selected_tags %}active{% endif %}">
                        <input type="checkbox" name="tags" value="{{ tag.id }}" class="d-none"
                            {% if tag.id in selected_tags %}checked{% endif %}>
                        {{ tag.name }}
                    </label>
                {% endfor %}
            </div>
            <small class="form-text text-muted">Hold down the Ctrl (Windows) or Command (Mac) button to select multiple options.</small>
        </div>

        <div class="d-flex justify-content-between">
            <button type="submit" class="btn btn-success">{% if object %}Update Blog{% else %}Create Blog{% endif %}</button>
            <a href="{% url 'blog-list' %}" class="btn btn-secondary">Cancel</a>
        </div>
    </form>
    {% else %}
    <p>You must be logged in to create or edit blog posts.</p>
    {% endif %}
</div>

<script>
    // JavaScript to handle the toggling of tag button state
    document.querySelectorAll('#tag-buttons .btn').forEach(button => {
        button.addEventListener('click', function(event) {
            event.preventDefault();  // Prevent the default label click behavior
            this.classList.toggle('active');  // Toggle the active class

            const input = this.querySelector('input');  // Get the hidden checkbox input
            input.checked = !input.checked;  // Toggle the checked state of the checkbox
        });
    });
</script>
{% endblock %}

blog/templates/blog_list.html
{% extends 'base.html' %}

{% block title %}Blogs{% endblock %}

{% block content %}
<h2>Blogs</h2>

<form method="get" class="mb-4" id="filter-form">
    <div class="form-row">
        <div class="form-group col-md-4">
            <label for="tag">Filter by Tag:</label>
            <select name="tag" id="tag" class="form-control" onchange="this.form.submit()">
                <option value="">All Tags</option>
                {% for tag in tags %}
                    <option value="{{ tag.id }}" {% if request.GET.tag == tag.id|stringformat:"i" %}selected{% endif %}>{{ tag.name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group col-md-4">
            <label for="author">Filter by Author:</label>
            <select name="author" id="author" class="form-control" onchange="this.form.submit()">
                <option value="">All Authors</option>
                {% for author in authors %}
                    <option value="{{ author.id }}" {% if request.GET.author == author.id|stringformat:"i" %}selected{% endif %}>{{ author.last_name }} {{ author.first_name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group col-md-4 d-flex align-items-end">
            <button type="button" class="btn btn-secondary me-2" onclick="clearFilters()">Clear Filters</button>
        </div>
    </div>
</form>

<script>
    function clearFilters() {
        document.getElementById('tag').selectedIndex = 0;
        document.getElementById('author').selectedIndex = 0;
        document.getElementById('filter-form').submit();
    }
</script>

{% if blogs %}
    <div class="blog-list">
    {% regroup blogs by published_month as blog_groups %}

    {% for group in blog_groups %}
        <h3 class="mt-4">{{ group.grouper|date:"F Y" }}</h3>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Author</th>
                    <th>Published</th>
                    <th>Tags</th> <!-- New column for Tags -->
                </tr>
            </thead>
            <tbody>
                {% for blog in group.list %}
                    <tr>
                        <td><a href="{% url 'blog-detail' blog.id %}">{{ blog.title }}</a></td>
                        <td>{{ blog.author.last_name }} {{ blog.author.first_name }}</td>
                        <td>{{ blog.published_date|date:"F j, Y" }}</td>
                        <td>
                            {% for tag in blog.tags.all %}
                                <span class="badge bg-info p-2">{{ tag.name }}</span> <!-- Display tags -->
                            {% endfor %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% endfor %}
    </div>
{% else %}
    <p>No blog posts available.</p>
{% endif %}
{% endblock %}

blog/templates/user_blog_list.html
{% extends 'base.html' %}

{% block title %}My Blogs{% endblock %}

{% block content %}
<h2>My Blogs</h2>

{% if blogs %}
<div class="blog-list">
    {% regroup blogs by published_month as blog_groups %}
    
    {% for group in blog_groups %}
        <h3 class="mt-4">{{ group.grouper|date:"F Y" }}</h3>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Published</th>
                    <th>Actions</th>
                    <th>Tags</th>
                </tr>
            </thead>
            <tbody>
                {% for blog in group.list %}
                    <tr>
                        <td><a href="{% url 'blog-detail' blog.id %}">{{ blog.title }}</a></td>
                        <td>{{ blog.published_date|date:"F j, Y" }}</td>
                        <td>
                            {% for tag in blog.tags.all %}
                                <span class="badge bg-info p-2">{{ tag.name }}</span> <!-- Display tags -->
                            {% endfor %}
                        </td>
                        <td>
                            <a href="{% url 'blog-edit' blog.id %}" class="btn btn-sm btn-primary">Edit</a>
                            <a href="{% url 'blog-delete' blog.id %}" class="btn btn-sm btn-danger">Delete</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% endfor %}
</div>
{% else %}
    <p>No blog posts available.</p>
{% endif %}
{% endblock %}